Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: 
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements 
c) Divide every element by 2 

In [1]:
import numpy as np
a = np.array([2,3,4,5,6])
print(a+2)
print(a*3)
print(a/2)

[4 5 6 7 8]
[ 6  9 12 15 18]
[1.  1.5 2.  2.5 3. ]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_valuex = np.bincount(x).argmax()
most_freq_valuey = np.bincount(y).argmax()
indicex = np.where(x == most_freq_valuex)[0]
indicey = np.where(y == most_freq_valuex)[0]
print("Most Frequent Value in x:", most_freq_valuex)
print("Indices of Most Frequent Value:", indicex)
print("Most Frequent Value in y:", most_freq_valuey)
print("Indices of Most Frequent Value:", indicey)

[5 4 6 3 2 1]
Most Frequent Value in x: 1
Indices of Most Frequent Value: [0 5 7 8 9]
Most Frequent Value in y: 1
Indices of Most Frequent Value: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column 

In [3]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print("1st row, 2nd column: ", arr[0][1])
print("3rd row, 1st column: ", arr[2][0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column:  20
3rd row, 1st column:  70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute?

In [4]:
naman = np.linspace(10,100,25)
print(naman)
print("Dimensions: ", naman.ndim)
print("Shape: ", naman.shape)
print("Total Elements: ", naman.size)
print("Datatype: ", naman.dtype)
print("No. of bytes: ", naman.nbytes)
print("Transpose: ", naman.reshape(25,1))
# print("Transpose: ", naman.T)             # Yes

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions:  1
Shape:  (25,)
Total Elements:  25
Datatype:  float64
No. of bytes:  200
Transpose:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_name>>.

In [5]:
ucs420_naman = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_naman)
print("Mean: ", np.mean(ucs420_naman))
print("Median: ", np.median(ucs420_naman))
print("Max: ", np.max(ucs420_naman))
print("Min: ", np.min(ucs420_naman))
print("Unique Elements: ", np.unique(ucs420_naman))

reshaped_ucs420_naman = ucs420_naman.reshape(4,3)
print(reshaped_ucs420_naman)

resized_ucs420_naman = np.resize(ucs420_naman, (2,3))
print(resized_ucs420_naman)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean:  43.333333333333336
Median:  37.5
Max:  90
Min:  10
Unique Elements:  [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
